bases:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
