bases:
  - ../../base

nameSuffix: -prod

commonLabels:
  environment: prod

patches:
  # Patch for Deployment replicas
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 4

  # Patch for Service port and nodePort
  - target:
      kind: Service
      name: nginx-service
    patch: |
      - op: replace
        path: /spec/ports/0/port
        value: 8080
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8080
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081
