bases:
  - ../../base

nameSuffix: -prod

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: nginx-deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 4

