apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80          # Service port
      targetPort: 80    # Container port
      nodePort: 30080   # NodePort (optional, Minikube will assign one if you omit)
